remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: The Stochastic Parrot
description: The official blog site for Relinvent
show_downloads: false

# Navigation settings
header_pages:
  - about.md
  - contact.md
